name: Run tests
on:
  push:
    branches:
    # Only mainline branches, features etc are covered on the pull_request trigger
    - '*.x'
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        php_version:
        - '8.1'
        - '8.2'
        - '8.3'
        dependency-versions:
        - 'default'

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}
        tools: composer:v2

    - name: Checkout
      uses: actions/checkout@v4
      with:
        show-progress: false

    - name: Install composer dependencies
      uses: ramsey/composer-install@v3
      with:
        dependency-versions: ${{ matrix.dependency-versions }}

    - name: Run unit tests
      run: |
        vendor/bin/phpunit
